### ISSUE TITLE
Problem installing MineMeld on Ubuntu 16.04 using Ansible

### ISSUE THREAD

**Issue by vedd3r** [PaloAltoNetworks/minemeld#11]
Hi,

I encountered the below error at npm install stage. Below is the error. 

TASK [minemeld : npm install] ***************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["npm", "install"], "delta": "0:01:53.179532", "end": "2017-09-28 16:20:48.060202", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-09-28 16:18:54.880670", "stderr": "npm WARN package.json minemeldWebui@0.9.42 No repository field.\nnpm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css\nnpm WARN deprecated bower@1.7.9: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467\nnpm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.\nnpm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more information\nnpm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no\nnpm WARN peerDependencies longer be automatically installed to fulfill the peerDependency \nnpm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.\nnpm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130\nnpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.\nnpm WARN engine browser-sync-client@2.5.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine request@2.81.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated node-uuid@1.4.7: Use uuid module instead\nnpm WARN engine esprima@4.0.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-validator@4.2.1: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN optional dep failed, continuing fsevents@1.1.2\nnpm WARN optional dep failed, continuing fsevents@1.1.2\nnpm WARN optional dep failed, continuing fsevents@1.1.2\nnpm WARN engine har-schema@1.0.5: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine request@2.83.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-validator@5.0.3: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine hawk@6.0.2: wanted: {\"node\":\">=4.5.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN engine cryptiles@3.1.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine boom@4.3.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine hoek@4.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine sntp@2.0.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-schema@2.0.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine boom@5.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN deprecated express@2.5.11: express 2.x series is deprecated\nnpm WARN deprecated connect@1.9.2: connect 1.x series is deprecated\nnpm WARN engine xmlbuilder@9.0.4: wanted: {\"node\":\">=4.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\n/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5\nconst Hoek = require('hoek');\n^^^^^\nSyntaxError: Use of const in strict mode.\n    at exports.runInThisContext (vm.js:73:16)\n    at Module._compile (module.js:443:25)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.<anonymous> (/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\ngyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/0.12.2\"\ngyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/.node-gyp\"\ngyp ERR! build error \ngyp ERR! stack Error: not found: make\ngyp ERR! stack     at F (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:40:28)\ngyp ERR! stack     at E (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:43:29)\ngyp ERR! stack     at /opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:54:16\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)\ngyp ERR! System Linux 4.4.0-62-generic\ngyp ERR! command \"node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate\ngyp ERR! node -v v0.12.2\ngyp ERR! node-gyp -v v1.0.3\ngyp ERR! not ok \ngyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/0.12.2\"\ngyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/.node-gyp\"\ngyp ERR! build error \ngyp ERR! stack Error: not found: make\ngyp ERR! stack     at F (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:40:28)\ngyp ERR! stack     at E (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:43:29)\ngyp ERR! stack     at /opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:54:16\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)\ngyp ERR! System Linux 4.4.0-62-generic\ngyp ERR! command \"node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil\ngyp ERR! node -v v0.12.2\ngyp ERR! node-gyp -v v1.0.3\ngyp ERR! not ok \nnpm WARN optional dep failed, continuing utf-8-validate@1.2.2\nnpm WARN optional dep failed, continuing bufferutil@1.2.1\nnpm ERR! Linux 4.4.0-62-generic\nnpm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"\nnpm ERR! node v0.12.2\nnpm ERR! npm  v2.7.4\nnpm ERR! code ELIFECYCLE\n\nnpm ERR! node-sass@3.13.1 install: `node scripts/install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.\nnpm ERR! This is most likely a problem with the node-sass package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node scripts/install.js\nnpm ERR! You can get their info via:\nnpm ERR!     npm owner ls node-sass\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /opt/minemeld/www/webui/npm-debug.log", "stderr_lines": ["npm WARN package.json minemeldWebui@0.9.42 No repository field.", "npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css", "npm WARN deprecated bower@1.7.9: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467", "npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.", "npm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more information", "npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no", "npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency ", "npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.", "npm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm", "npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.", "npm WARN deprecated node-uuid@1.4.8: Use uuid module instead", "npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130", "npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.", "npm WARN engine browser-sync-client@2.5.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine request@2.81.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated node-uuid@1.4.7: Use uuid module instead", "npm WARN engine esprima@4.0.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-validator@4.2.1: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN optional dep failed, continuing fsevents@1.1.2", "npm WARN optional dep failed, continuing fsevents@1.1.2", "npm WARN optional dep failed, continuing fsevents@1.1.2", "npm WARN engine har-schema@1.0.5: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine request@2.83.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-validator@5.0.3: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine hawk@6.0.2: wanted: {\"node\":\">=4.5.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN engine cryptiles@3.1.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine boom@4.3.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine hoek@4.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine sntp@2.0.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-schema@2.0.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine boom@5.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN deprecated express@2.5.11: express 2.x series is deprecated", "npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated", "npm WARN engine xmlbuilder@9.0.4: wanted: {\"node\":\">=4.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5", "const Hoek = require('hoek');", "^^^^^", "SyntaxError: Use of const in strict mode.", "    at exports.runInThisContext (vm.js:73:16)", "    at Module._compile (module.js:443:25)", "    at Object.Module._extensions..js (module.js:478:10)", "    at Module.load (module.js:355:32)", "    at Function.Module._load (module.js:310:12)", "    at Module.require (module.js:365:17)", "    at require (module.js:384:17)", "    at Object.<anonymous> (/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)", "    at Module._compile (module.js:460:26)", "    at Object.Module._extensions..js (module.js:478:10)", "gyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/0.12.2\"", "gyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/.node-gyp\"", "gyp ERR! build error ", "gyp ERR! stack Error: not found: make", "gyp ERR! stack     at F (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:40:28)", "gyp ERR! stack     at E (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:43:29)", "gyp ERR! stack     at /opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:54:16", "gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)", "gyp ERR! System Linux 4.4.0-62-generic", "gyp ERR! command \"node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"", "gyp ERR! cwd /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate", "gyp ERR! node -v v0.12.2", "gyp ERR! node-gyp -v v1.0.3", "gyp ERR! not ok ", "gyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/0.12.2\"", "gyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/.node-gyp\"", "gyp ERR! build error ", "gyp ERR! stack Error: not found: make", "gyp ERR! stack     at F (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:40:28)", "gyp ERR! stack     at E (/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:43:29)", "gyp ERR! stack     at /opt/minemeld/www/venv/lib/node_modules/npm/node_modules/which/which.js:54:16", "gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)", "gyp ERR! System Linux 4.4.0-62-generic", "gyp ERR! command \"node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"", "gyp ERR! cwd /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil", "gyp ERR! node -v v0.12.2", "gyp ERR! node-gyp -v v1.0.3", "gyp ERR! not ok ", "npm WARN optional dep failed, continuing utf-8-validate@1.2.2", "npm WARN optional dep failed, continuing bufferutil@1.2.1", "npm ERR! Linux 4.4.0-62-generic", "npm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"", "npm ERR! node v0.12.2", "npm ERR! npm  v2.7.4", "npm ERR! code ELIFECYCLE", "", "npm ERR! node-sass@3.13.1 install: `node scripts/install.js`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.", "npm ERR! This is most likely a problem with the node-sass package,", "npm ERR! not with npm itself.", "npm ERR! Tell the author that this fails on your system:", "npm ERR!     node scripts/install.js", "npm ERR! You can get their info via:", "npm ERR!     npm owner ls node-sass", "npm ERR! There is likely additional logging output above.", "", "npm ERR! Please include the following file with any support request:", "npm ERR!     /opt/minemeld/www/webui/npm-debug.log"], "stdout": "\n> deasync@0.1.1 install /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync\n> node ./build.js\n\n`linux-x64-node-0.12` exists; testing\nBinary is fine; exiting\n\n> phantomjs@1.9.20 install /opt/minemeld/www/webui/node_modules/phantomjs\n> node install.js\n\nPhantomJS not found on PATH\nDownloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2\nSaving to /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2\nReceiving...\n\nReceived 12854K total.\nExtracting tar contents (via spawned process)\nRemoving /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom\nCopying extracted folder /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1506586829476/phantomjs-1.9.8-linux-x86_64 -> /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom\nWriting location.js file\nDone. Phantomjs binary available at /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom/bin/phantomjs\n\n> node-sass@3.13.1 install /opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass\n> node scripts/install.js\n\n\n> utf-8-validate@1.2.2 install /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate\n> node-gyp rebuild\n\n\n> bufferutil@1.2.1 install /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil\n> node-gyp rebuild", "stdout_lines": ["", "> deasync@0.1.1 install /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync", "> node ./build.js", "", "`linux-x64-node-0.12` exists; testing", "Binary is fine; exiting", "", "> phantomjs@1.9.20 install /opt/minemeld/www/webui/node_modules/phantomjs", "> node install.js", "", "PhantomJS not found on PATH", "Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2", "Saving to /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2", "Receiving...", "", "Received 12854K total.", "Extracting tar contents (via spawned process)", "Removing /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom", "Copying extracted folder /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1506586829476/phantomjs-1.9.8-linux-x86_64 -> /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom", "Writing location.js file", "Done. Phantomjs binary available at /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom/bin/phantomjs", "", "> node-sass@3.13.1 install /opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass", "> node scripts/install.js", "", "", "> utf-8-validate@1.2.2 install /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate", "> node-gyp rebuild", "", "", "> bufferutil@1.2.1 install /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil", "> node-gyp rebuild"]}

**Comment by vedd3r** [comment]
Futher checking on the npm-debug.log showed this error

215463 verbose stack Error: node-sass@3.13.1 install: `node scripts/install.js`
215463 verbose stack Exit status 1
215463 verbose stack     at EventEmitter.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
215463 verbose stack     at EventEmitter.emit (events.js:110:17)
215463 verbose stack     at ChildProcess.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/spawn.js:14:12)
215463 verbose stack     at ChildProcess.emit (events.js:110:17)
215463 verbose stack     at maybeClose (child_process.js:1015:16)
215463 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
215464 verbose pkgid node-sass@3.13.1
215465 verbose cwd /opt/minemeld/www/webui
215466 error Linux 4.4.0-62-generic
215467 error argv "/opt/minemeld/www/venv/bin/node" "/opt/minemeld/www/venv/bin/npm" "install"
215468 error node v0.12.2
215469 error npm  v2.7.4
215470 error code ELIFECYCLE
215471 error node-sass@3.13.1 install: `node scripts/install.js`
215471 error Exit status 1
215472 error Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
215472 error This is most likely a problem with the node-sass package,
215472 error not with npm itself.
215472 error Tell the author that this fails on your system:
215472 error     node scripts/install.js
215472 error You can get their info via:
215472 error     npm owner ls node-sass
215472 error There is likely additional logging output above.
