### ISSUE TITLE
FATAL Exited too quickly - minemeld-engine & minemeld-web 

### ISSUE THREAD

**Issue by cuongdinh** [PaloAltoNetworks/minemeld#17]
Hello,
I'm trying to install a new instance of Minemeld on Ubuntu 14 using instruction https://live.paloaltonetworks.com/t5/MineMeld-Articles/Manually-install-MineMeld-on-Ubuntu-Server-14-04/ta-p/98454

and I couldn't log in. I found that the minemeld-engine and minemeld-web couldn't start. Below is some log. Any suggestion? Thanks!

sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/local/supervisor/config/supervisord.conf status
minemeld-engine                  FATAL     Exited too quickly (process log may have details)
minemeld-supervisord-listener    RUNNING   pid 8868, uptime 0:34:30
minemeld-traced                  RUNNING   pid 8870, uptime 0:34:30
minemeld-web                     FATAL     Exited too quickly (process log may have details)

Below is the minemeld-engine.log log:

AttributeError: 'module' object has no attribute 'get_installed_distributions'
2018-05-08T15:31:58 (8893)launcher.main INFO: Starting mm-run.py version 0.9.44
2018-05-08T15:31:58 (8893)launcher.main INFO: mm-run.py arguments: Namespace(config='/opt/minemeld/local/config', multiprocessing=0, nodes_per_chassis=15.0, verbose=False)
Traceback (most recent call last):
  File "/opt/minemeld/engine/current/bin/mm-run", line 11, in <module>
    sys.exit(main())
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/launcher.py", line 218, in main
    config = minemeld.run.config.load_config(args.config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 567, in load_config
    return _load_config_from_dir(config_path)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 382, in _load_config_from_dir
    ccvalid, cconfig = _load_and_validate_config_from_file(ccpath)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 281, in _load_and_validate_config_from_file
    valid = resolve_prototypes(config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 477, in resolve_prototypes
    prototypes_entrypoints = minemeld.loader.map(minemeld.loader.MM_PROTOTYPES_ENTRYPOINT)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 105, in map
    _initialize_entry_point_group(entrypoint_group)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 55, in _initialize_entry_point_group
    installed = _installed_versions()
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 29, in _installed_versions
    installed_dists = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
2018-05-08T15:32:01 (8918)launcher.main INFO: Starting mm-run.py version 0.9.44
2018-05-08T15:32:01 (8918)launcher.main INFO: mm-run.py arguments: Namespace(config='/opt/minemeld/local/config', multiprocessing=0, nodes_per_chassis=15.0, verbose=False)
Traceback (most recent call last):
  File "/opt/minemeld/engine/current/bin/mm-run", line 11, in <module>
    sys.exit(main())
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/launcher.py", line 218, in main
    config = minemeld.run.config.load_config(args.config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 567, in load_config
    return _load_config_from_dir(config_path)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 382, in _load_config_from_dir
    ccvalid, cconfig = _load_and_validate_config_from_file(ccpath)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 281, in _load_and_validate_config_from_file
    valid = resolve_prototypes(config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 477, in resolve_prototypes
    prototypes_entrypoints = minemeld.loader.map(minemeld.loader.MM_PROTOTYPES_ENTRYPOINT)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 105, in map
    _initialize_entry_point_group(entrypoint_group)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 55, in _initialize_entry_point_group
    installed = _installed_versions()
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 29, in _installed_versions
    installed_dists = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
2018-05-08T15:32:05 (8947)launcher.main INFO: Starting mm-run.py version 0.9.44
2018-05-08T15:32:05 (8947)launcher.main INFO: mm-run.py arguments: Namespace(config='/opt/minemeld/local/config', multiprocessing=0, nodes_per_chassis=15.0, verbose=False)
Traceback (most recent call last):
  File "/opt/minemeld/engine/current/bin/mm-run", line 11, in <module>
    sys.exit(main())
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/launcher.py", line 218, in main
    config = minemeld.run.config.load_config(args.config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 567, in load_config
    return _load_config_from_dir(config_path)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 382, in _load_config_from_dir
    ccvalid, cconfig = _load_and_validate_config_from_file(ccpath)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 281, in _load_and_validate_config_from_file
    valid = resolve_prototypes(config)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/run/config.py", line 477, in resolve_prototypes
    prototypes_entrypoints = minemeld.loader.map(minemeld.loader.MM_PROTOTYPES_ENTRYPOINT)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 105, in map
    _initialize_entry_point_group(entrypoint_group)
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 55, in _initialize_entry_point_group
    installed = _installed_versions()
  File "/opt/minemeld/engine/0.9.44/local/lib/python2.7/site-packages/minemeld/loader.py", line 29, in _installed_versions
    installed_dists = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'

**Comment by xhoms** [comment]
Hi @cuongdinh ,

faced the same a few days ago and used the strategy described at <https://live.paloaltonetworks.com/t5/MineMeld-Discussions/New-minemeld-deploy-unable-to-login-to-GUI/m-p/211175/highlight/true#M2096> to workaround it while it is fixed.
