### ISSUE TITLE
No Module Named datetime

### ISSUE THREAD

**Issue by EdoardoMDP** [PaloAltoNetworks/minemeld#39]
Hi all,

I have updated ubuntu server from version 14.04.05 to 16.04.06.

When i run the follow command :

$ sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/local/supervisor/config/supervisord.conf status
i got the follow error:

noModulNamedDateTime.png

Someone could help me?

Thanks

**Comment by EdoardoMDP** [comment]
the error is this:

`Traceback (most recent call last) :
 File "opt/minemeld/engine/current/bin/supervisorctl " , line 6, in <module> from supervisor . supervisorctl import main 
File "opt/minemeId/engine/0.9.52.post 1/ local/lib/python2.7/site-packages/supervisor/superuvisorctI.py line 36, in <module> from supervisor.options import ClientOptions 
File "opt/minemeId/engine0.9.52.post1/ local/lib/python2.7/site-packages/supervisor/options.py, line 15, in <module> import pkg_resources Fi le "opt/minemeId/engine0.9.52.post1/ local/lib/python2.7/site-packages/pkg_resources/__init__.py , line 35, in <module> import plistlib 
File "usr/lib/python2.7/plistlib.py" , line 62, in import <module> datetime ImportError: No module named datetime`

**Comment by AbhinavBat** [comment]
Hi @EdoardoMDP ,

How you fixed this issue. I am facing the same.
Please can you help me on this..

My email id is : singh.abhinav56@gmail.com, appreciate buddy if you can help me on this..

**Comment by juthak** [comment]
Hi @EdoardoMDP 

I am facing the same

In my case:  i did upgrade distro from ubuntu 16.04 to 20.04 and minemeld using version 0.9.70.

# **sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/supervisor/config/supervisord.conf status**

**this result when i ran that above command.**

`Traceback (most recent call last):
  File "/opt/minemeld/engine/current/bin/supervisorctl", line 5, in <module>
    from supervisor.supervisorctl import main
  File "/opt/minemeld/engine/0.9.70.post1/local/lib/python2.7/site-packages/supervisor/supervisorctl.py", line 36, in <module>
    from supervisor.options import ClientOptions
  File "/opt/minemeld/engine/0.9.70.post1/local/lib/python2.7/site-packages/supervisor/options.py", line 15, in <module>
    import pkg_resources
  File "/opt/minemeld/engine/0.9.70.post1/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/opt/minemeld/engine/0.9.70.post1/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 61, in load_module
    "distribution.".format(**locals())
ImportError: The 'packaging.requirements' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.`


Could you help this issue, what's worng with me?


Update 29/11/2022
Many reseach I think it about  python version 2.7 not support on ubuntu 20.04  and minemeld webUI 0.9.70 is using python 2.7
Ref. https://wiki.ubuntu.com/FocalFossa/ReleaseNotes
